services:
  jupyter-gemini:
    build: .
    container_name: jupyter_gemini_env
    working_dir: /app/gemini
    ports:
      - "8889:8889"
    volumes:
      - ..:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
